# Generated by Django 2.2.3 on 2019-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190913_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
