# Generated by Django 2.2.3 on 2019-09-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_blogpost_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='img',
            new_name='image',
        ),
    ]
