# Generated by Django 2.2.3 on 2019-10-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
