# Generated by Django 2.2.3 on 2019-10-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
    ]
