# Generated by Django 2.2.3 on 2019-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20191103_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
