# Generated by Django 2.2.3 on 2019-11-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_delete_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
