# Generated by Django 2.2.3 on 2019-11-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, default=True),
        ),
    ]
