# Generated by Django 2.2.3 on 2019-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_auto_20191116_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
